name: wordini
description: "Build your personal vocabulary list with Wordini. Collect words, find definitions, do quizzes and monitor your progress with in-built reports."
publish_to: 'none'
version: 1.2.4+4

environment:
  sdk: ^3.6.0

dependencies:
  dart_openai: ^5.1.0
  flutter:
    sdk: flutter
  http: ^1.4.0
  path_provider: ^2.1.4
  envied: ^1.3.2
  timezone: ^0.10.1
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  fl_chart: ^0.71.0
  percent_indicator: ^4.2.5
  syncfusion_flutter_gauges: ^29.1.38
  csv: ^6.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  flutter_colorpicker: ^1.1.0
  google_sign_in: ^7.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # hive_generator: ^2.0.1
  riverpod_generator: ^2.6.3
  build_runner: ^2.5.4
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  envied_generator: ^1.1.1
  
#! fix analyzer issues with riverpod_lint & hive_generator so it can be upgraded in future

flutter:
  uses-material-design: true
  assets:
    - assets/